apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.myapp }}
  template:
    metadata:
      labels:
        app: {{ .Values.myapp }}
    spec:
      containers:
        - name: myapp-container
          image: katarzynadasilva/myapp-k8s-py:dernier_version
          env:
            - name: KATARZYNA
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KATARZYNA
          ports:
            - containerPort: 5001
          resources:
            limits:
              cpu: "0.5"  
              memory: "512Mi"  
            requests:
              cpu: "0.1"  
              memory: "256Mi"
