apiVersion: apps/v1
kind: Deployment
metadata:
  # Name of the deployment
  name: myapp
spec:
  # Number of desired replicas
  replicas: 3
  # Selector for pods managed by this deployment
  selector:
    matchLabels:
       name: myapp
  # Pod template
  template:
    metadata:
      # Labels for the pods
      labels:
         name: myapp
    spec:
      # Containers within the pod
      containers:
        - name: myapp-container
          # Docker image for the container
          image: katarzynadasilva/myapp-k8s-py:v1
          # Environment variables for the container
          env:
            - name: KATARZYNA
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KATARZYNA
          # Ports exposed by the container
          ports:
            - containerPort: 5001
          # Resource limits for the container
          resources:
            limits:
              cpu: "0.5"  
              memory: "512Mi"  
            requests:
              cpu: "0.1"  
              memory: "256Mi"
