apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-volume-new  # Name of the persistent volume
spec:
  capacity:
    storage: 1Gi  # Capacity of the volume, set to 1 gigabyte
  accessModes:
    - ReadWriteOnce  # Access mode specifying that the volume can be mounted as read-write by a single node
  persistentVolumeReclaimPolicy: Retain  # Policy specifying what should happen to the volume after it's released, set to "Retain"
  storageClassName: standard  # Storage class name for dynamic provisioning
  hostPath:
    path: "/mnt/data"  # Path on the host machine where the volume will be mounted
