apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myapp-storage  # Name of the persistent volume claim
spec:
  accessModes:
    - ReadWriteOnce  # Access mode specifying that the volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 1Gi  # Requesting 1 gigabyte of storage for the volume
