apiVersion: v1
kind: Service
metadata:
  # Name of the service
  name: myapp-service
spec:
  # Selectors for the pods to which this service routes traffic
  selector:
     name: myapp
  # Ports configuration
  ports:
    - protocol: TCP
      # Port on the service
      port: 80
      # Port on the pods
      targetPort: 5001
  # Type of service (LoadBalancer in this case)
  type: LoadBalancer
