apiVersion: v1
kind: Pod
metadata:
  name: flask-app
spec:
  containers:
  - name: flask-app
    image: <nazwa_obrazu>
    env:
    - name: VOTREPRENOM
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: VOTREPRENOM
